/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_hectorreyes;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Onasis Reyes
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_registrarUsuario = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jT_nombreUsuario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jT_nombre = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSp_calidadWifi = new javax.swing.JSpinner();
        jT_apellido = new javax.swing.JTextField();
        btn_aggUsuario = new javax.swing.JButton();
        jT_telefono = new javax.swing.JTextField();
        jT_contraseña = new javax.swing.JPasswordField();
        jD_login = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_ingresarLogin = new javax.swing.JButton();
        jT_usuarioLogin = new javax.swing.JTextField();
        jT_contraseñaLogin = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        jD_aggAmigos = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_buscarUsuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jT_buscarAmigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_aggUsuario = new javax.swing.JTable();
        btn_enviarSolicitud = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jD_solicitudes = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTbl_solicitudes = new javax.swing.JTable();
        btn_aceptarSoli = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_amigos = new javax.swing.JList<>();
        btn_enviarMensaje = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMI_login = new javax.swing.JMenuItem();
        jMI_registrar = new javax.swing.JMenuItem();
        jMI_aggAmigos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel13.setText("Telefono");

        jLabel14.setText("Usuario");

        jLabel15.setText("Cotraseña");

        jLabel16.setText("Nombre");

        jLabel17.setText("Calidad del Wifi");

        jLabel18.setText("Apellido");

        jSp_calidadWifi.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        btn_aggUsuario.setText("Registrar");
        btn_aggUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aggUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_aggUsuario)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel13)
                                .addComponent(jLabel16)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jT_telefono)
                                        .addComponent(jT_apellido)
                                        .addComponent(jT_nombre)
                                        .addComponent(jT_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jT_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(18, 18, 18)
                            .addComponent(jSp_calidadWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jT_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jT_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jT_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jT_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jSp_calidadWifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_aggUsuario)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jD_registrarUsuarioLayout = new javax.swing.GroupLayout(jD_registrarUsuario.getContentPane());
        jD_registrarUsuario.getContentPane().setLayout(jD_registrarUsuarioLayout);
        jD_registrarUsuarioLayout.setHorizontalGroup(
            jD_registrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jD_registrarUsuarioLayout.setVerticalGroup(
            jD_registrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        btn_ingresarLogin.setText("Ingresar");
        btn_ingresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarLoginActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("LOGIN");

        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_registrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ingresarLogin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_usuarioLogin)
                            .addComponent(jT_contraseñaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_usuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jT_contraseñaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ingresarLogin)
                    .addComponent(btn_registrar))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jD_loginLayout = new javax.swing.GroupLayout(jD_login.getContentPane());
        jD_login.getContentPane().setLayout(jD_loginLayout);
        jD_loginLayout.setHorizontalGroup(
            jD_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_loginLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jD_loginLayout.setVerticalGroup(
            jD_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_loginLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btn_buscarUsuario.setText("Buscar");
        btn_buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese usuario que desea buscar");

        jTbl_aggUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre de Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbl_aggUsuario);
        if (jTbl_aggUsuario.getColumnModel().getColumnCount() > 0) {
            jTbl_aggUsuario.getColumnModel().getColumn(0).setResizable(false);
        }

        btn_enviarSolicitud.setText("Enviar Solicitud");
        btn_enviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarSolicitudActionPerformed(evt);
            }
        });

        jLabel4.setText("Nota: Solo se puede enviar solicitud un usuario a la vez.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jT_buscarAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_buscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_enviarSolicitud)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jT_buscarAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_enviarSolicitud)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jD_aggAmigosLayout = new javax.swing.GroupLayout(jD_aggAmigos.getContentPane());
        jD_aggAmigos.getContentPane().setLayout(jD_aggAmigosLayout);
        jD_aggAmigosLayout.setHorizontalGroup(
            jD_aggAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jD_aggAmigosLayout.setVerticalGroup(
            jD_aggAmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        jTbl_solicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre de Usuario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTbl_solicitudes);
        if (jTbl_solicitudes.getColumnModel().getColumnCount() > 0) {
            jTbl_solicitudes.getColumnModel().getColumn(0).setResizable(false);
        }

        btn_aceptarSoli.setText("Aceptar Solicitud");
        btn_aceptarSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarSoliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_aceptarSoli)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_aceptarSoli)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jD_solicitudesLayout = new javax.swing.GroupLayout(jD_solicitudes.getContentPane());
        jD_solicitudes.getContentPane().setLayout(jD_solicitudesLayout);
        jD_solicitudesLayout.setHorizontalGroup(
            jD_solicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jD_solicitudesLayout.setVerticalGroup(
            jD_solicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Amigos");

        jList_amigos.setModel(new DefaultListModel());
        jList_amigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_amigosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList_amigos);

        btn_enviarMensaje.setText("Enviar Mensaje");
        btn_enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarMensajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_enviarMensaje)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_enviarMensaje)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jMenu2.setText("File");
        jMenu2.setEnabled(false);

        jMI_login.setText("Login");
        jMI_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_loginActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_login);

        jMI_registrar.setText("Registrar");
        jMI_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_registrarActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_registrar);

        jMI_aggAmigos.setText("Agregar Amigos");
        jMI_aggAmigos.setEnabled(false);
        jMI_aggAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_aggAmigosActionPerformed(evt);
            }
        });
        jMenu2.add(jMI_aggAmigos);

        jMenuItem1.setText("Solicitudes Recibidas");
        jMenuItem1.setEnabled(false);
        jMenu2.add(jMenuItem1);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aggUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aggUsuarioActionPerformed
        // TODO add your handling code here:
        if (jT_nombreUsuario.getText().equals("")
                || jT_contraseña.getText().equals("")
                || jT_nombre.getText().equals("")
                || jT_apellido.getText().equals("")
                || jT_telefono.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Porfavor llene todos los campos.");
        } else {
            boolean existe = false;
            administradorUsuario adminUs = new administradorUsuario("./usuarios.lab");
            adminUs.cargarArchivo();
            Usuario usuario = new Usuario(
                    jT_nombreUsuario.getText(),
                    jT_contraseña.getText(),
                    Integer.parseInt(jSp_calidadWifi.getValue().toString()),
                    jT_nombre.getText(),
                    jT_apellido.getText(),
                    jT_telefono.getText());
            for (int i = 0; i < adminUs.getUsuarios().size(); i++) {
                if (adminUs.getUsuarios().get(i).getNombreUsuario().equals(usuario.getNombreUsuario())) {
                    JOptionPane.showMessageDialog(this, "El nombre de usuario ya existe, intenta con otro.");
                    existe = true;
                }
            }//fin for
            if (existe == false) {
                adminUs.añadirUsuario(usuario);
                adminUs.escribirArchivo();
                usuarioActual = usuario;
                JOptionPane.showMessageDialog(this, "Se ha registrado con éxito.");
                jD_registrarUsuario.dispose();
                jD_login.dispose();
            }
        }
    }//GEN-LAST:event_btn_aggUsuarioActionPerformed

    private void btn_buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarUsuarioActionPerformed
        // TODO add your handling code here:
        administradorUsuario adminUs = new administradorUsuario("./usuarios.lab");
        adminUs.cargarArchivo();
        boolean existe = false;
        limpiarTablaBuscarAmigos();
        for (int i = 0; i < adminUs.getUsuarios().size(); i++) {
            if (!adminUs.getUsuarios().get(i).getNombreUsuario().equals(usuarioActual.getNombreUsuario())) {
                if (jT_buscarAmigo.getText().equals(adminUs.getUsuarios().get(i).getNombreUsuario())) {
                    DefaultTableModel model = (DefaultTableModel) jTbl_aggUsuario.getModel();
                    String[] nRow = {adminUs.getUsuarios().get(i).getNombreUsuario()};
                    model.addRow(nRow);
                    existe = true;
                    jTbl_aggUsuario.setModel(model);
                }//fin if
            }//fin if
        }//fin for
        if (existe == false) {
            JOptionPane.showMessageDialog(this, "No se ha encontrado ningún usuario.");
        }
    }//GEN-LAST:event_btn_buscarUsuarioActionPerformed

    private void btn_ingresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarLoginActionPerformed
        // TODO add your handling code here:
        if (jT_usuarioLogin.getText().equals("")
                || jT_contraseñaLogin.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Porfavor llene todos los campos.");
        } else {
            boolean login = false;
            administradorUsuario adminUs = new administradorUsuario("./usuarios.lab");
            adminUs.cargarArchivo();
            for (int i = 0; i < adminUs.getUsuarios().size(); i++) {
                if (adminUs.getUsuarios().get(i).getNombreUsuario().equals(jT_usuarioLogin.getText())
                        && adminUs.getUsuarios().get(i).getContraseña().equals(jT_contraseñaLogin.getText())) {
                    usuarioActual = adminUs.getUsuarios().get(i);
                    login = true;
                    jMI_aggAmigos.setEnabled(true);
                    jD_login.dispose();
                    JOptionPane.showMessageDialog(this, "Bienvenido.");
                }
            }//fin for
            if (login == false) {
                JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrectos.");
            }
        }
    }//GEN-LAST:event_btn_ingresarLoginActionPerformed

    private void btn_enviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarSolicitudActionPerformed
        // TODO add your handling code here:
        if (enviarSolicitud == true) {
            administradorUsuario adminUs = new administradorUsuario("./usuarios.lab");
            adminUs.cargarArchivo();
            String nameUsuario = jTbl_aggUsuario.getValueAt(0, 0).toString();
            for (int i = 0; i < adminUs.getUsuarios().size(); i++) {
                if (adminUs.getUsuarios().get(i).getNombreUsuario().equals(nameUsuario)) {
                    if (!adminUs.getUsuarios().get(i).getSolicitudes().contains(usuarioActual)) {//si falla borrar
                        adminUs.getUsuarios().get(i).getSolicitudes().add(usuarioActual);
                        JOptionPane.showMessageDialog(this, "Se ha enviado una solicitud.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Ya le has enviado una solicitud.");
                    }
                }
            }
        }
    }//GEN-LAST:event_btn_enviarSolicitudActionPerformed

    private void jMI_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_loginActionPerformed
        // TODO add your handling code here:
        jD_login.setModal(true);
        jD_login.pack();
        jD_login.setLocationRelativeTo(null);
        jD_login.setVisible(true);
    }//GEN-LAST:event_jMI_loginActionPerformed

    private void jMI_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_registrarActionPerformed
        // TODO add your handling code here:
        jD_registrarUsuario.setModal(true);
        jD_registrarUsuario.pack();
        jD_registrarUsuario.setLocationRelativeTo(null);
        jD_registrarUsuario.setVisible(true);
    }//GEN-LAST:event_jMI_registrarActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
        jD_login.dispose();
        jD_registrarUsuario.setModal(true);
        jD_registrarUsuario.pack();
        jD_registrarUsuario.setLocationRelativeTo(null);
        jD_registrarUsuario.setVisible(true);
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void jMI_aggAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_aggAmigosActionPerformed
        // TODO add your handling code here:
        jD_aggAmigos.setModal(true);
        jD_aggAmigos.pack();
        jD_aggAmigos.setLocationRelativeTo(null);
        jD_aggAmigos.setVisible(true);
    }//GEN-LAST:event_jMI_aggAmigosActionPerformed

    private void btn_aceptarSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarSoliActionPerformed
        // TODO add your handling code here:
        administradorUsuario adminUS = new administradorUsuario("");
        adminUS.cargarArchivo();
        if (usuarioActual.getSolicitudes().size() < 0) {
            JOptionPane.showMessageDialog(this, "No existen usuarios");
        } else {
            if (jTbl_solicitudes.getSelectedRow() >= 0) {

                for (int i = 0; i < adminUS.getUsuarios().size(); i++) {
                    if (adminUS.getUsuarios().get(i).
                            equals(usuarioActual.getSolicitudes().get(jTbl_solicitudes.getSelectedRow()))) {
                        usuarioActual.getAmigos().add(adminUS.getUsuarios().get(i));
                        usuarioActual.getSolicitudes().remove(jTbl_solicitudes.getSelectedRow());
                        adminUS.getUsuarios().get(i).getAmigos().add(usuarioActual);
                    }
                }

                DefaultTableModel model = (DefaultTableModel) jTbl_solicitudes.getModel();
                model.removeRow(jTbl_solicitudes.getSelectedRow());
                jTbl_solicitudes.setModel(model);

                DefaultListModel modelList = (DefaultListModel) jList_amigos.getModel();
                modelList.addElement(adminUS.getUsuarios().get(jTbl_solicitudes.getSelectedRow()));
                jList_amigos.setModel(modelList);

                JOptionPane.showMessageDialog(this, "Se ha aceptado una solicitud.");
            } else {
                JOptionPane.showMessageDialog(this, "No has seleccionado ningún usuario.");
            }
        }

    }//GEN-LAST:event_btn_aceptarSoliActionPerformed

    private void jList_amigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_amigosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList_amigosMouseClicked

    private void btn_enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarMensajeActionPerformed
        // TODO add your handling code here:
        if (usuarioActual.getAmigos().size() <= 0) {
            JOptionPane.showMessageDialog(this, "No tienes amigos agregados.");
        } else if (rootPaneCheckingEnabled) {
            JOptionPane.showMessageDialog(this, "No has seleccioado ningun amigo de la lista.");
        } else {
            JOptionPane.showMessageDialog(this, "Se ha enviado un mensaje.");
        }
    }//GEN-LAST:event_btn_enviarMensajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void cargarTablaSolicitudes() {
        limpiarTablaSolicitudes();
        DefaultTableModel model = (DefaultTableModel) jTbl_solicitudes.getModel();
        for (int i = 0; i < usuarioActual.getSolicitudes().size(); i++) {
            String nRow[] = {usuarioActual.getSolicitudes().get(i).getNombreUsuario()};
            model.addRow(nRow);
        }
        jTbl_solicitudes.setModel(model);
    }

    public void cargarLogin() {
        limpiarTablaBuscarAmigos();
        cargarTablaSolicitudes();
    }

    public void limpiarTablaSolicitudes() {
        jTbl_solicitudes.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre de Usuario"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }

    public void limpiarTablaBuscarAmigos() {
        jTbl_aggUsuario.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre de Usuario"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptarSoli;
    private javax.swing.JButton btn_aggUsuario;
    private javax.swing.JButton btn_buscarUsuario;
    private javax.swing.JButton btn_enviarMensaje;
    private javax.swing.JButton btn_enviarSolicitud;
    private javax.swing.JButton btn_ingresarLogin;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JDialog jD_aggAmigos;
    private javax.swing.JDialog jD_login;
    private javax.swing.JDialog jD_registrarUsuario;
    private javax.swing.JDialog jD_solicitudes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList_amigos;
    private javax.swing.JMenuItem jMI_aggAmigos;
    private javax.swing.JMenuItem jMI_login;
    private javax.swing.JMenuItem jMI_registrar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSp_calidadWifi;
    private javax.swing.JTextField jT_apellido;
    private javax.swing.JTextField jT_buscarAmigo;
    private javax.swing.JPasswordField jT_contraseña;
    private javax.swing.JPasswordField jT_contraseñaLogin;
    private javax.swing.JTextField jT_nombre;
    private javax.swing.JTextField jT_nombreUsuario;
    private javax.swing.JTextField jT_telefono;
    private javax.swing.JTextField jT_usuarioLogin;
    private javax.swing.JTable jTbl_aggUsuario;
    private javax.swing.JTable jTbl_solicitudes;
    // End of variables declaration//GEN-END:variables
    private Usuario usuarioActual;
    private final boolean enviarSolicitud = false;
}
